name: tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2, 8.3]
        laravel: [11.*, 10.*, 9.*]
        dependency-version: [prefer-lowest, prefer-stable]
        exclude:
          - php: 8.1
            laravel: 11.*

    name: Tests on PHP${{ matrix.php }} - Laravel${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    services:
      chroma:
        image: chromadb/chroma
        ports:
          - 8000:8000

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-L${{ matrix.laravel }}-${{ matrix.dependency-version }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, mbstring, zip
          coverage: none

      - name: Require Laravel Version
        run: >
          composer require
          "laravel/framework:${{ matrix.laravel }}"
          --no-interaction --no-update

      - name: Install Composer dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: Integration Tests
        run: php ./vendor/bin/pest
